name: Deploy packages to Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install modules
        run: bun install
      - name: Create packages
        run: |
          bun run package
          mv output.ts github-backup-${{ github.ref_name }}.ts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            github-backup-${{ github.ref_name }}.ts
    permissions:
      contents: write
